name: xarray-alos2-tests
channels:
  - conda-forge
dependencies:
  - ipython
  - pre-commit
  - pytest
  - pytest-reportlog
  - pytest-cov
  - numpy
  - toolz
  - cytoolz
  - python-dateutil
  - construct
  - fsspec
  - xarray
  - xarray-datatree
  - dask
  - distributed
  - aiohttp
  - requests
