name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-skip-ci-trigger:
    name: "Detect CI Trigger: [skip-ci]"
    if: |
      github.repository == 'umr-lops/xarray-ceos-alos2'
      && github.event_name == 'push'
      || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.detect-trigger.outputs.trigger-found }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: xarray-contrib/ci-trigger@v1
        id: detect-trigger
        with:
          keyword: "[skip-ci]"

  ci:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    needs: detect-skip-ci-trigger

    if: needs.detect-skip-ci-trigger.outputs.triggered == 'false'

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          # need to fetch all tags to get a correct version
          fetch-depth: 0 # fetch all branches and tags

      - name: Setup environment variables
        run: |
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

          echo "CONDA_ENV_FILE=ci/requirements/environment.yaml" >> $GITHUB_ENV

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ${{ env.CONDA_ENV_FILE }}
          environment-name: xarray-ceos-alos2-tests
          cache-environment: true
          cache-environment-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
          create-args: >-
            python=${{matrix.python-version}}
            conda

      - name: Install xarray-ceos-alos2
        run: |
          python -m pip install --no-deps -e .

      - name: Import xarray-ceos-alos2
        run: |
          python -c "import ceos_alos2"

      - name: Run tests
        run: |
          python -m pytest --cov=ceos_alos2
